---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test
kind: template
load: plugin.starlark
data:
  stepName: my_step
  image: my_image
  commands: my_command

